Uberi/speech_recognition

- speech_recognition/__init__.py
When enabled, the speech recognition is constantly re-evaluating the ambient noise and resetting the energy threshold.
There are a few pieces to this feature.
1) Make sure to set a *high* energy_threshold to start or the energy_threshold will trigger entering the phrase state before the ambient noise floor can be evaluated. (2000 worked for me)
2) dynamic_energy_threshold_decay (0.0-1.0) is the rate at which the energy_threshold chases the ambient noise floor. A numbers closer to 0 means that the energy_thereshold will follow more quickly. Nubmer closer to 1.0 follow more slowly
3) dynamic_energy_threshold_ratio_above_ambient. This is the "gap" between the ambient noise and the threshold. Setting to 1.0 would mean the energy_threshold will equalize at the same as ambient. 1.0 would be a …
> Added dynamic_energy_threshold capability

- speech_recognition/__init__.py
Adds an ``offset`` parameter to Recognizer.record(), ideal for chunk processing.
May help with Uberi's #22.
> Add ``offset`` parameter to Recognizer.record()

- speech_recognition/__init__.py
As some devices (I.E, RPI usb external microphone input) require different rates / chunk_sizes, it'd be nice to have it parametrized.
> Added support for more rates

- reference/library-reference.rst
- speech_recognition/__init__.py
Optionally define `session_id` parameter to identify the client and enable dialog / context mode
> Added Api.ai session_id as optional parameter

- speech_recognition/__init__.py
Adjusted version of Wit.ai Speech API do prevent "Depricated Warning"
> Fixed Wit.ai API version

- speech_recognition/__init__.py
> new bing speech api

- speech_recognition/__init__.py
Without this you need to `brew install flac` to get it working on a Mac
> Correct path for flac-mac

- speech_recognition/__init__.py
> phrase_time_limit was ignored on listen_in_background call

- speech_recognition/__init__.py
Fix known docker issue when trying to execute binary right after doing chmod
Also forward `Recognizer.operation_timeout` to googleapiclient API timeout
This issue causes `OSError: "Text file busy"` exception in `get_flac_converter()`
> ............
>      text = recognizer.recognize_google_cloud(audio, credentials_json=api_key, language=language)
>    File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 815, in recognize_google_cloud
>     convert_width=2  # audio samples must be 16-bit
>    File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 439, in get_flac_data
>      ], stdin=subprocess.PIPE, stdout=subprocess.PIPE, startupinfo=startup_info)
>    File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
> …
> fix chmod+exec issue when running on docker

- .github/workflows/unittests.yml
This is temporary workaround in #626.
This will be merged after passing all tests.
> Pin pocketsphinx temporarily

- README.rst
- examples/threaded_workers.py
- reference/pocketsphinx.rst
- setup.py
- speech_recognition/__init__.py
- speech_recognition/__main__.py
- tests/test_audio.py
> Drop inactive Python

- .gitignore
Make it as easy as possible for many people to develop with standard .gitignore
> Standardize .gitignore

- .github/workflows/unittests.yml
- setup.py
- speech_recognition/__init__.py
- speech_recognition/recognizers/google.py
- tests/test_recognition.py
> Run tests in Python 3.11

- .github/workflows/unittests.yml
- setup.py
- speech_recognition/__init__.py
- speech_recognition/recognizers/google.py
- tests/recognizers/test_google.py
- tests/test_recognition.py
> Refactor recognize_google

- .github/workflows/rstcheck.yml
found https://github.com/Uberi/speech_recognition/blob/3.10.3/README.rst?plain=1#L304
> Migrate rstcheck from TravisCI

- speech_recognition/audio.py
Fix https://github.com/Uberi/speech_recognition/issues/655
> Support M1 Mac

- speech_recognition/recognizers/google.py
- tests/recognizers/test_google.py
> Enable to pass SSL endpoint to cope with WinError 10054 

- setup.py
> Install aifc and audioop in Python 3.13

- setup.cfg
> Fix "SetuptoolsDeprecationWarning: bdist_wheel.universal is deprecated"

- .github/workflows/unittests.yml
- README.rst
- setup.cfg
- speech_recognition/__init__.py
- speech_recognition/recognizers/groq.py
- speech_recognition/recognizers/whisper_api.py
- tests/recognizers/test_groq.py
> Support Groq whisper

- .github/workflows/rstcheck.yml
- README.rst
- reference/library-reference.rst
- speech_recognition/__init__.py
- speech_recognition/recognizers/groq.py
- tests/recognizers/test_groq.py
* Support Groq's optional parameters
* Refine RESPX test code
* Remove `GROQ_API_KEY` check code (Only groq is responsible)
> Tweak Groq code

- .github/workflows/unittests.yml
- README.rst
- examples/microphone_recognition.py
- reference/library-reference.rst
- setup.cfg
- speech_recognition/recognizers/openai.py
* Only openai library is responsible for `OPENAI_API_KEY`
* Rename extra
> Remove `api_key` parameter for OpenAI client

- .github/workflows/lint.yml
```yaml
- run: pipx run flake8 --ignore=E501,E701,W503 .
```
> Use pipx to lint simpler and faster

- .github/workflows/unittests.yml
- Makefile
- README.rst
- reference/library-reference.rst
- setup.cfg
- speech_recognition/__init__.py
- speech_recognition/recognizers/google_cloud.py
- tests/recognizers/test_google_cloud.py
* Add tests
* Add extra to install
* Bugfix: `enable_word_time_offsets` parameter is not CamelCase
* Remove dead code
> Add tests (google-cloud-speech)

- .github/workflows/unittests.yml
Workaround for https://github.com/Uberi/speech_recognition/actions/runs/12764934158/job/35578064016
> hotfix: Pass CI to release 3.14.0
