speech_recognition/__init__.py

This stops the “OSError: [Errno Input overflowed] -9981” from
interrupting program flow when doing listen_in_background().
I had issue #70 as well, this pull request fixes it. 
See this [Stack Exchange](http://stackoverflow.com/a/35168465/5935090) answer for a tiny bit more detail.

Fixed: read suppresses errors on overflow

---

speech_recognition/__init__.py

Tried to get a list of all microphones which resulted in an error because the static method 'list_microphone_names' tries to access self. Fixed it in a way that keeps the import checks for pyaudio intact.
If you would like any changes just let me know.

Fixed static method 'list_microphone_names' accessing non existing self

---

examples/wav_transcribe.py
speech_recognition/__init__.py

I added a method in the Recognizer class to support queries to the api.ai speech recognition engine (https://api.ai/). I also added an example usage to wav_transcribe.py. Api.ai supports a lot of languages, but I made English the default. Also, api.ai only accepts 16k audio.

Api ai support

---

speech_recognition/__init__.py

recognize_api was always raising an UnknownValueError even though the returned JSON contained the correctly transcribed text. I changed the logic for raising the error.

changed logic for recognize_api to riase a UnknownValueError

---

README.rst
speech_recognition/__init__.py

This uses the API call that is explicitly limited to 60 seconds input length because currently the call without this limitation [may return empty results](https://code.google.com/p/google-cloud-platform/issues/detail?id=158) for longer input dependent on sample rate. Once that's resolved this could switch to the other call more practically.
Resolves #128.

Add Google Cloud Speech API support

---

speech_recognition/__init__.py

Fixes https://github.com/Uberi/speech_recognition/issues/177
Removed checking for "transcript" key since the Speech API should always be returning that.

Always return transcription with highest confidence in recognize_google()

---

speech_recognition/__init__.py

You will be able to reproduce the problem with the attached wav files (that were zipped). nok.wav is the "problematic sample". ok.wav works fine.
To reproduce the problem, just call google_recognize with the given wav file and **language="pt-BR"**. It should break your application when trying to decode nok.wav. If you print what was transcribed, you will see:
{'alternative': [{'transcript': 'jogador do Palmeiras foi o único que nasceu 3 vezes'}, {'transcript': 'jogador do Palmeiras foi o único que nasceu três vezes'}, {'transcript': 'jogador do Palmeiras foi o único que nas outras vezes'}, {'transcript': 'jogador do Palmeiras foi o único que nasceu o 3 vezes'}, {'transcript': 'jogador do Palmeiras foi o único que nasceu o três vezes'}], 'final': True}
And there is no confidence in this …

Treats the situation when google API is called and no confidence is returned

---

speech_recognition/__init__.py

If you're using the latest version of google-api-python-client (1.6.2) which uses oauth2client 4.0.0, then you will see these tracebacks on every call to recognize_google_cloud()
```
2017-04-26 01:09:47,839 WARNING -- __init__.py:44 -- file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
File "/home/ubuntu/.virtualenvs/v/lib/python3.4/site-packages/googleapiclient/discovery_
cache/__init__.py", line 36, in autodetect
from google.appengine.api import memcache
ImportError: No module named 'google'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/ubuntu/.virtualenvs/v/lib/python3.4/site-packages/googleapiclient/discovery_
cache/file_cache.py", line 33, in <module>
from …
```

Silence oauth2client tracebacks when using Google Cloud Speech API

---

speech_recognition/__init__.py

Google is going to deprecate v1beta1 resource for Cloud Speech API on November 30, 2017
This change updates usage of v1beta1 resource to v1 (along with parameter and function names)

updated usage of Google Cloud Speech API from v1beta1 to v1

---

reference/library-reference.rst
speech_recognition/__init__.py

This pull request adds a parameter to recognize_sphinx. This parameter, config, enables to set the location of the various files used by PocketSphinx. This is useful when using lmtools (http://www.speech.cs.cmu.edu/tools/lmtool-new.html) to generate specific dictionary and language model files. This make pocketsphinx fast and accurate over limited vocabularies (e.g. voice commands)

PocketSphinx customization

---

examples/tensorflow_commands.py
speech_recognition/__init__.py

Tensorflow audio commands recognition as shown here: https://www.tensorflow.org/versions/master/tutorials/audio_recognition
Model and Label file can be downloaded here: http://download.tensorflow.org/models/speech_commands_v0.01.zip
An example can be like this:
import speech_recognition as sr
r = sr.Recognizer()
m = sr.Microphone()
def callback(recognizer, audio):
try:
spoken = recognizer.recognize_tensorflow(audio, tensor_graph='speech_recognition/tensorflow-data/conv_actions_frozen.pb', tensor_label='speech_recognition/tensorflow-data/conv_actions_labels.txt')
print(spoken)
with m as source:
r.adjust_for_ambient_noise(source)
stop_listening = r.listen_in_background(m, callback, phrase_time_limit=1)

Tensorflow

---

speech_recognition/__init__.py

Getting 
File "/home/chriamue/Temp/speech_recognition/speech_recognition/__init__.py", line 188, in __exit__
self.stream.close()
File "/home/chriamue/Temp/speech_recognition/speech_recognition/__init__.py", line 203, in close
if not self.pyaudio_stream.is_stopped():
File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 543, in is_stopped
return pa.is_stream_stopped(self._stream)
OSError: [Errno -9988] Stream closed
because the microphone stream is always closed with finally.
Terminating it only if exceptions occur should fix it.

Fix for OSError: [Errno -9988] Stream closed Error

---

speech_recognition/__init__.py

Greetings
Added the ```pfilter``` parameter to adjust the profanity level in ```recognize_google```. The value is sent in the request to the Google Speech Recognition API as the ```pFilter``` parameter. Added a line to the function description explaining the new parameter.
Jorge

Add paramater to change profanity filter level for Google Speech Recognition

---

README.rst
speech_recognition/__init__.py

The `oauth2client` and `googleapiclient` libraries are deprecated -- this PR switches the `recognize_google_cloud` method to use the `google-cloud-speech` library instead, which is recommended.

Google cloud speech library

---

speech_recognition/__init__.py

Hello.
Current code collect really large buffer and put in snowboy detect every time where new chunk reading, without clearing. This create large cpu consumption - 80-85% on my orange pi.
I change it, using an algorithm similar to [snowboydecoder.py](https://github.com/Kitt-AI/snowboy/blob/master/examples/Python3/snowboydecoder.py) (put smaller buffer and clear after). This decrease cpu usage to 4%.
I use similar code on [my project](https://github.com/Aculeasis/mdmTerminal2/blob/master/src/lib/sr_wrapper.py#L98) and this works without problems.

Fix large cpu consumption in snowboy detect

---

README.rst
examples/audio_transcribe.py
examples/microphone_recognition.py
make-release.sh
speech_recognition/__init__.py

The Bing Speech API is deprecated and has been replaced with the Azure Speech API.  This PR added functionality for Azure Speech API.  Once the Bing Speech API has been completely removed, another PR can be added to delete that code.

Replace Bing Speech API with Azure Speech API

---

.travis.yml
README.rst
reference/library-reference.rst
speech_recognition/__init__.py
tests/test_recognition.py
tests/test_special_features.py

Fixes build and test failures in Travis CI.
The failure in 3.3 is caused by https://github.com/PyCQA/pyflakes/commit/a13dbe6652f2635b1a7e094a8eb8d27aec3f6c3f which drops pyflakes support for 3.3.

Fix Travis build

---

README.rst
speech_recognition/__init__.py

Now, speechrecognition supports offline API called vosk: https://github.com/alphacep/vosk-api
It is completly free and requires no api key

Added Vosk API and updated README

---

speech_recognition/__init__.py

There is a small typo in speech_recognition/__init__.py.
Should read `convert` rather than `covnert`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, covnert -> convert

---

.github/workflows/unittests.yml
speech_recognition/__init__.py
tests/test_recognition.py

Fix unit tests of recognize_google method

---

.github/workflows/unittests.yml

Unit tests are passed in Python 3.9 on GitHub Action (ref: https://github.com/Uberi/speech_recognition/pull/619#issuecomment-1195411485),
so I expanded the Python version from 3.7 to 3.10.
I will later modify metadata for PyPI on a separate pull request.

Run unittests on pull requests

---

.github/workflows/unittests.yml
README.rst
examples/microphone_recognition.py
reference/library-reference.rst
speech_recognition/__init__.py
tests/test_recognition.py

Solve https://github.com/Uberi/speech_recognition/issues/624 by adding recognize_whisper to Recognizer.
This works by writing in a tempfile, due to the format whisper asks for.
Usage example:
```python
import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:
print("Say something!")
audio = r.listen(source)
print("Got it, now to recognize it...")
try:
print("Whisper thinks you said " + r.recognize_whisper(audio, language='english'))
except sr.UnknownValueError:
print("Whisper could not understand audio")
except sr.RequestError as e:
print("Whisper error; {0}".format(e))
```

[feat(whisper)] Add recognize_whisper

---

speech_recognition/recognizers/whisper.py
tests/test_recognition.py

In November OpenAI released version 1.0 that deprecated a lot of old API.
These changes addresses issues raised in #720 and fixes now completely broken `recognize_whisper_api` API.

Updated to the latest OpenAI API changes, and fixed #720

---

speech_recognition/__init__.py

Support for receiving captured audio one chunk at a time, while continuing to use the wakeword and audio energy detection code.
Notably, Coqui.ai/DeepSpeech (the python STT package) support a streaming interface, which greatly improves interaction latency for continuous listening applications. Even for non-streaming interfaces, this implementation allows for eager encoding (for example converting to numpy buffers, or even precomputing transformer KVs), or just an earlier start to transmission (when using websockets or other chunked transfer mechanisms). 
Note: This is a minimal extraction from a larger edit I have in a side project. There, I ended up carving up huge chunks of recognizer to make it a bit more observable (i.e. trigger events based on speech detection start/stop aside from …

Add `stream=` kwarg to `Recognizer.listen`

---

setup.cfg
setup.py
speech_recognition/__init__.py

Only assemblyai needs requests

Tidy dependencies: requests

---

.github/workflows/unittests.yml
tests/test_whisper_recognition.py

Run tests on Python 3.13 (excluding whisper-local)

---

tests/recognizers/test_openai.py

bbf6753a01da27049789fa2f000b2e9885f54992 enables us to
* Pass `language` parameter (fix #681)
* Pass `prompt` parameter (#676)

Add tests for OpenAI optional parameters

---

.github/workflows/lint.yml
.github/workflows/rstcheck.yml
Makefile
README.rst
setup.cfg

refactor: Use pipx for lint and rstcheck

---

README.rst
speech_recognition/recognizers/google_cloud.py
tests/recognizers/test_google_cloud.py

SpeechRecognition should not be responsible for `GOOGLE_APPLICATION_CREDENTIALS`.
Same as groq and openai case

feat(google-cloud-speech): Delegate to google-auth

---

README.rst
examples/audio_transcribe.py
examples/extended_results.py
examples/microphone_recognition.py
examples/special_recognizer_features.py
reference/library-reference.rst
speech_recognition/recognizers/google_cloud.py
tests/recognizers/test_google_cloud.py

Signature: ``recognizer_instance.recognize_google_cloud(audio_data: AudioData, credentials_json_path: str | None = None, **kwargs) -> str | google.cloud.speech_v1.types.RecognizeResponse``
Usage
```python
_ = recognizer_instance.recognize_google_cloud(
audio_data,
language_code="ja-JP",
preferred_phrases=["numero", "hoge"],
use_enhanced=True,
)
```

Refine google_cloud recognizer's parameters

---

.github/workflows/unittests.yml
README.rst
reference/library-reference.rst
setup.cfg
speech_recognition/__init__.py
speech_recognition/recognizers/whisper_local/base.py
speech_recognition/recognizers/whisper_local/faster_whisper.py
speech_recognition/recognizers/whisper_local/whisper.py
tests/recognizers/whisper_local/test_faster_whisper.py
tests/recognizers/whisper_local/test_whisper.py

ref: #693, #800
```python
import speech_recognition as sr
r = sr.Recognizer()
with sr.AudioFile("path/to/audio_file.wav") as source:
audio_data = r.listen(source)
transcription = r.recognize_faster_whisper(audio_data)
```

Support Faster Whisper (with less copy and paste)

---

LICENSE.txt
README.rst

Fix https://github.com/Uberi/speech_recognition/pull/816 (Deleted. "Update LICENSE.txt, fix copyright license year")
ref(Japanese): https://zenn.dev/dalance/articles/7ecaf9369324c1#%E5%B9%B4%E5%BA%A6%E3%82%92%E6%9B%B4%E6%96%B0%E3%81%99%E3%81%B9%E3%81%8D%E3%81%AA%E3%81%AE%E3%81%8B

chore: Make copyright year of license not need to update

---

.github/workflows/unittests.yml
README.rst
reference/library-reference.rst
setup.cfg
speech_recognition/__init__.py
speech_recognition/recognizers/pocketsphinx.py
tests/test_special_features.py

Fix PocketSphinx tests failure on ubuntu-24.04

---

speech_recognition/recognizers/whisper_api/openai.py

Support gpt-4o-transcribe and gpt-4o-mini-transcribe

---

examples/audio_transcribe.py
examples/extended_results.py
examples/special_recognizer_features.py
speech_recognition/audio.py
speech_recognition/recognizers/whisper_api/openai.py
speech_recognition/recognizers/whisper_local/faster_whisper.py
tests/test_audio.py
tests/test_recognition.py
tests/test_special_features.py

Delete boilerplate code as refactoring first step

refactor: Extract logic as AudioData.from_file()

---

speech_recognition/recognizers/whisper_api/base.py
speech_recognition/recognizers/whisper_api/openai.py

* `--prompt` from [Whisper prompting guide](https://cookbook.openai.com/examples/whisper_prompting_guide)
* `--verbose` to debug transcription API call (whether `prompt` passed or not)

Add --prompt & --verbose in `python -m speech_recognition.recognizers.whisper_api.openai`

---

.github/workflows/unittests.yml
setup.cfg
setup_vosk.py
tests/recognizers/test_vosk.py

Add test recognize_vosk()

---

reference/library-reference.rst
speech_recognition/recognizers/vosk.py
tests/recognizers/test_vosk.py

Close https://github.com/Uberi/speech_recognition/pull/592

Add verbose parameter to recognize_vosk()
